apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: vs-game-server-fleet
spec:
  replicas: 1
  scheduling: Packed

  # Not sure which strategy to use: https://agones.dev/site/docs/guides/fleet-updates/
  strategy:
    type: Recreate

  template:
    spec:
      ports:
        - name: default
          containerPort: 7777

      # The GameServer's Pod template
      template:
        spec:
          tolerations:
          - key: kubernetes.azure.com/scalesetpriority
            operator: Equal
            value: 'spot'
            effect: NoSchedule

          containers:
            - name: vs-game-server
              image: poutypouchgamesacrcentralus.azurecr.io/vs-server:0.1.12
              resources:
                requests:
                  memory: 1000Mi
                  cpu: 970m # Side car requests 30m with no limit, but seems to take more than that.
                limits:
                  memory: 2000Mi
                  cpu: 970m
